name: Build and push docker image

on:
  push:
    tags:
    - 'release-*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Get tag version
       id: get_version
       uses: battila7/get-version-action@v2
     - name: Login to DockerHub
       uses: docker/login-action@v1.8.0
       with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        # registry: ${{ secrets.DOCKERHUB_REGISTRY }}
     - name: Build and push
       id: docker_build
       uses: docker/build-push-action@v2.3.0
       with:
        push: true
        tags: kocoler/nlpmicrobekg_frontend:latest
